#!/usr/bin/env bash

# Script for backing up https://github.com/partio-scout/kipa events
# @author ville.pekkinen@gmail.com, 2022

set -o errexit
set -o nounset

main() {
  source .env
  BACKUP_URL="http://${HOST}:${PORT}/kipa/${EVENT_NAME}/tallenna/"
  echo $BACKUP_URL
  TIMESTAMP=$(date)
  BACKUP_FILE="${BACKUP_REPO_DIR}/backup.xml"

  curl --verbose --fail --output "${BACKUP_FILE}" "${BACKUP_URL}"

  cd ${BACKUP_REPO_DIR}
 
  git add .

  if git commit -m "${TIMESTAMP}"; then
    git push
  fi
}

main
